config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'highlight#index'

  get 'home/index', to: 'highlight#index', as: :home
  get 'projects', to: 'project#index', as: :project
  get 'education', to: 'education#index', as: :education
  get 'history', to: 'gallary#history', as: :history_gallary
  get 'backend', to: 'highlight#backend', as: :backend_root

  scope :backend do
    get 'home', to: 'highlight#backend', as: :backend
    get 'projects', to: 'project#backend', as: :backend_projects
    get 'education', to: 'education#backend', as: :backend_education
    get 'gallary', to: 'gallary#backend', as: :backend_gallary
    get 'tools', to: 'tools#backend', as: :backend_tools

    scope :admin do
      scope :profile do
        get 'new', to: 'admin#new_profile', as: :new_profile
        get 'edit/:id', to: 'admin#edit_profile', as: :edit_profile
        post 'create', to: 'admin#create_profile', as: :create_profile
        patch 'update/:id', to: 'admin#update_profile', as: :update_profile
      end

      scope :social do
        get 'new', to: 'admin#new_social', as: :new_social
        get 'edit/:id', to: 'admin#edit_social', as: :edit_social
        post 'create', to: 'admin#create_social', as: :create_social
        patch 'update/:id', to: 'admin#update_social', as: :update_social
        delete 'delete/:id', to: 'admin#destroy_social', as: :delete_social
      end
    end
  end

  scope :highlight do
    get 'new', to: 'highlight#new', as: :new_highlight
    get 'edit/:id', to: 'highlight#edit', as: :edit_highlight
    post 'create', to: 'highlight#create', as: :create_highlight
    patch 'update/:id', to: 'highlight#update', as: :update_highlight
    delete 'delete/:id', to: 'highlight#destroy', as: :delete_highlight
  end

  scope :project do
    get 'new', to: 'project#new', as: :new_project
    get 'edit/:id', to: 'project#edit', as: :edit_project
    post 'create', to: 'project#create', as: :create_project
    patch 'update/:id', to: 'project#update', as: :update_project
    delete 'delete/:id', to: 'project#destroy', as: :delete_project
  end

  scope :education do
    scope :qualification do
      get 'details/:id', to: 'education#qualification_details', as: :qualification_details
      get 'new', to: 'education#new_qualification', as: :new_qualification
      post 'create', to: 'education#create_qualification', as: :create_qualification
      get 'edit/:id', to: 'education#edit_qualification', as: :edit_qualification
      patch 'update/:id', to: 'education#update_qualification', as: :update_qualification
      delete 'delete/:id', to: 'education#destroy_qualification', as: :delete_qualification
    end

    scope :year do
      get 'new/:qualification', to: 'education#new_year', as: :new_year
      get 'edit/:id', to: 'education#edit_year', as: :edit_year
      post 'create/:qualification', to: 'education#create_year', as: :create_year
      patch 'update/:id', to: 'education#update_year', as: :update_year
      delete 'delete/:id', to: 'education#destroy_year', as: :delete_year
    end

    scope :unit do
      get 'new/:year', to: 'education#new_unit', as: :new_unit
      get 'edit/:id', to: 'education#edit_unit', as: :edit_unit
      post 'create/:year', to: 'education#create_unit', as: :create_unit
      patch 'update/:id', to: 'education#update_unit', as: :update_unit
      delete 'delete/:id', to: 'education#destroy_unit', as: :delete_unit
    end

    scope :tag do
      get 'new/:unit', to: 'tag#new', as: :new_tag
      post 'create/:unit', to: 'tag#create', as: :create_tag
      delete 'delete/:id', to: 'tag#destroy', as: :delete_tag
    end
  end

  scope :tools do
    get 'new', to: 'tools#new', as: :new_tool
    post 'create', to: 'tools#create', as: :create_tool
    delete 'delete/:id', to: 'tools#destroy', as: :delete_tool
  end
end

app/models/highlight.rb
# frozen_string_literal: true

class Highlight < ApplicationRecord
  validates_presence_of :title, :organisation, :start_date, :end_date,
                        :description
end

app/controllers/highlight_controller.rb
# frozen_string_literal: true

class HighlightController < ApplicationController
  layout 'backend', except: %i[index]

  before_action :set_highlight, only: %i[show edit update destroy]
  before_action :set_highlights, only: %i[index backend]
  before_action :set_tools, only: %i[index backend]

  http_basic_authenticate_with name: ENV['BACKEND_USERNAME'], password: ENV['BACKEND_PASSWORD'], except: %i[index]

  def index
    render 'frontend/home/index'
  end

  def backend
    @profile = Profile.all
    @socials = Social.all.order('position ASC')

    render 'backend/home/index'
  end

  def new
    @highlight = Highlight.new

    render 'backend/highlights/new'
  end

  def edit
    render 'backend/highlights/edit'
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @highlight = Highlight.new(highlight_params)

    respond_to do |format|
      if @highlight.save
        format.html { redirect_to backend_path, notice: 'highlight created' }
      else
        format.html { redirect_to backend_path, notice: 'failed to create' }
      end
    end
  end

  def update
    respond_to do |format|
      if @highlight.update(highlight_params)
        format.html { redirect_to backend_path, notice: 'highlight updated' }
      else
        format.html { redirect_to backend_path, notice: 'failed to update' }
      end
    end
  end

  def destroy
    @highlight.destroy
    respond_to do |format|
      format.html do
        redirect_to backend_path, notice: 'highlight removed'
      end
    end
  end

  private

  def set_highlights
    @highlights = Highlight.order('start_date DESC')
  end

  def set_highlight
    @highlight = Highlight.find(params[:id])
  end

  def set_tools
    @tools = Tool.all
  end

  def highlight_params
    params.require(:highlight).permit(:title, :organisation, :start_date, :end_date, :description, :url)
  end
end

app/views/backend/highlights/_list_all.html.erb
<div class='row'>
  <div class='col-lg-4'>
    <div class='heading'>
      <h3>Experience</h3>
      <h6 class='font-lite-black'>highlights</h6>
      <%= link_to 'new', new_highlight_path, class: 'focused-link' %>
    </div>
  </div>

  <div class='col-lg-8'>
    <div class='experience-wrapper'>
      <% @highlights.each do |highlight| %>
        <div class='experience margin-b-50'>
          <h4><%= highlight.title %></h4>
          <h5><%= highlight.organisation %></h5>
          <h6 class='font-lite-black margin-t-10'><%= duration_for(highlight) %></h6>
          <p class='margin-tb-10'><%= highlight.description %></p>
          <%= link_to 'more info', highlight.url, class: 'focused-link' unless highlight.url.empty? %>
          <%= link_to 'edit', edit_highlight_path(highlight), class: 'focused-link' %>
          <span class='or'>or</span>
          <%= link_to 'remove', delete_highlight_path(highlight), method: :delete, class: 'focused-link-danger', data: { confirm: 'Are you sure? This action can not be undone.' }%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/backend/highlights/edit.html.erb
<section class='section'>
  <div class='container'>
    <div class='row'>
      <div class='col-lg-4'>
        <div class='heading'>
          <h3>Update Highlight</h3>
        </div>
      </div>

      <div class='col-lg-8'>
        <%= form_with(model: @highlight, url: update_highlight_path) do |form| %>
          <div class='form-group'>
            <label>Job Title / Qualificiation:</label><span class='font-red'>*</span>
            <%= form.text_field :title, class: 'form-control', placeholder: 'Developer or BSc Software Engineering', required: true %>
          </div>

          <div class='form-group'>
            <label>Organisation:</label><span class='font-red'>*</span>
            <%= form.text_field :organisation, class: 'form-control', placeholder: 'UKCloud or Bournemouth University', required: true %>
          </div>

          <div class='form-row'>
            <div class='form-group'>
              <label>Start Date</label><span class='font-red'>*</span>
              <%= form.text_field :start_date, type: 'date', class: 'form-control', required: true%>
            </div>

            <div class='form-group'>
              <label>End Date (or leave blank)</label>
              <%= form.text_field :end_date, type: 'date', class: 'form-control' %>
            </div>
          </div>

          <div class='form-group'>
            <label>Description:</label><span class='font-red'>*</span>
            <%= form.text_area :description, class: 'form-control', placeholder: 'Type here...', rows: 4, required: true %>
          </div>

          <div class='form-group'>
            <label>URL: (optional)</label>
            <%= form.text_field :url, class: 'form-control', placeholder: 'http://url/page' %>
          </div>

          <hr>

          <%= form.submit 'Submit', class: 'focused-button' %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/backend/highlights/new.html.erb
<section class='section'>
  <div class='container'>
    <div class='row'>
      <div class='col-lg-4'>
        <div class='heading'>
          <h3>New Highlight</h3>
        </div>
      </div>

      <div class='col-lg-8'>
        <%= form_with(model: @highlight, url: create_highlight_path) do |form| %>
          <div class='form-group'>
            <label>Job Title / Qualificiation:</label><span class='font-red'>*</span>
            <%= form.text_field :title, class: 'form-control', placeholder: 'Developer or BSc Software Engineering', required: true %>
          </div>

          <div class='form-group'>
            <label>Organisation:</label><span class='font-red'>*</span>
            <%= form.text_field :organisation, class: 'form-control', placeholder: 'UKCloud or Bournemouth University', required: true %>
          </div>

          <div class='form-row'>
            <div class='form-group'>
              <label>Start Date</label><span class='font-red'>*</span>
              <%= form.text_field :start_date, type: 'date', class: 'form-control', required: true%>
            </div>

            <div class='form-group'>
              <label>End Date (or leave blank)</label>
              <%= form.text_field :end_date, type: 'date', class: 'form-control' %>
            </div>
          </div>

          <div class='form-group'>
            <label>Description:</label><span class='font-red'>*</span>
            <%= form.text_area :description, class: 'form-control', placeholder: 'Type here...', rows: 4, required: true %>
          </div>

          <div class='form-group'>
            <label>URL: (optional)</label>
            <%= form.text_field :url, class: 'form-control', placeholder: 'http://url/page' %>
          </div>

          <hr>

          <%= form.submit 'Submit', class: 'focused-button' %>
        <% end %>
      </div>
    </div>
  </div>
</section>